# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='service.proto',
  package='proto',
  syntax='proto3',
  serialized_options=b'\n\014com.test.rpcP\000',
  serialized_pb=b'\n\rservice.proto\x12\x05proto\"\x1f\n\x0fSayHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\x0c\"\"\n\x10SayHelloResponse\x12\x0e\n\x06result\x18\x01 \x01(\x0c\x32N\n\x0fSayHelloService\x12;\n\x08SayHello\x12\x16.proto.SayHelloRequest\x1a\x17.proto.SayHelloResponseB\x10\n\x0c\x63om.test.rpcP\x00\x62\x06proto3'
)




_SAYHELLOREQUEST = _descriptor.Descriptor(
  name='SayHelloRequest',
  full_name='proto.SayHelloRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='proto.SayHelloRequest.name', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=55,
)


_SAYHELLORESPONSE = _descriptor.Descriptor(
  name='SayHelloResponse',
  full_name='proto.SayHelloResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='proto.SayHelloResponse.result', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=91,
)

DESCRIPTOR.message_types_by_name['SayHelloRequest'] = _SAYHELLOREQUEST
DESCRIPTOR.message_types_by_name['SayHelloResponse'] = _SAYHELLORESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SayHelloRequest = _reflection.GeneratedProtocolMessageType('SayHelloRequest', (_message.Message,), {
  'DESCRIPTOR' : _SAYHELLOREQUEST,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:proto.SayHelloRequest)
  })
_sym_db.RegisterMessage(SayHelloRequest)

SayHelloResponse = _reflection.GeneratedProtocolMessageType('SayHelloResponse', (_message.Message,), {
  'DESCRIPTOR' : _SAYHELLORESPONSE,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:proto.SayHelloResponse)
  })
_sym_db.RegisterMessage(SayHelloResponse)


DESCRIPTOR._options = None

_SAYHELLOSERVICE = _descriptor.ServiceDescriptor(
  name='SayHelloService',
  full_name='proto.SayHelloService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=93,
  serialized_end=171,
  methods=[
  _descriptor.MethodDescriptor(
    name='SayHello',
    full_name='proto.SayHelloService.SayHello',
    index=0,
    containing_service=None,
    input_type=_SAYHELLOREQUEST,
    output_type=_SAYHELLORESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SAYHELLOSERVICE)

DESCRIPTOR.services_by_name['SayHelloService'] = _SAYHELLOSERVICE

# @@protoc_insertion_point(module_scope)
